// lex.yy.cpp generated by reflex 6.0.0 from tokens.l

#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_graphs_file         "sample1.gv"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_outfile             "lex.yy.cpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual int lex(void);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  int lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int Lexer::lex(void)
{
  static const char *REGEX_INITIAL = "(?m)((?:\\Q+\\E))|((?:\\Q-\\E))|((?:\\Q*\\E))|((?:\\Q/\\E))|((?:\\Q%\\E))|((?:\\Q==\\E))|((?:\\Q!=\\E))|((?:\\Q<=\\E))|((?:\\Q>=\\E))|((?:\\Q<\\E))|((?:\\Q>\\E))|((?:\\Q&&\\E))|((?:\\Q||\\E))|((?:\\Q!\\E))|((?:\\Q=\\E))|((?:\\Q;\\E))|((?:\\Q,\\E))|((?:\\Q(\\E))|((?:\\Q)\\E))|((?:\\Q{\\E))|((?:\\Q}\\E))|(-?[0-9]+)|([A-Z_a-z][0-9A-Z_a-z]*)|([\\x09\\x0a\\x0d\\x20]+)|((?:\\Q//\\E).*)|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
#line 4 "tokens.l"
/* PATTERN */                    /* ACTION */

  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return int();
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule tokens.l:4: "+" :
#line 4 "tokens.l"
return OP_ADD;
            break;
          case 2: // rule tokens.l:5: "-" :
#line 5 "tokens.l"
return OP_SUB;
            break;
          case 3: // rule tokens.l:6: "*" :
#line 6 "tokens.l"
return OP_MUL;
            break;
          case 4: // rule tokens.l:7: "/" :
#line 7 "tokens.l"
return OP_DIV;
            break;
          case 5: // rule tokens.l:8: "%" :
#line 8 "tokens.l"
return OP_MOD;


            break;
          case 6: // rule tokens.l:11: "==" :
#line 11 "tokens.l"
return OP_EQ;
            break;
          case 7: // rule tokens.l:12: "!=" :
#line 12 "tokens.l"
return OP_NE;
            break;
          case 8: // rule tokens.l:13: "<=" :
#line 13 "tokens.l"
return OP_LE;
            break;
          case 9: // rule tokens.l:14: ">=" :
#line 14 "tokens.l"
return OP_GE;
            break;
          case 10: // rule tokens.l:15: "<" :
#line 15 "tokens.l"
return OP_LT;
            break;
          case 11: // rule tokens.l:16: ">" :
#line 16 "tokens.l"
return OP_GT;


            break;
          case 12: // rule tokens.l:19: "&&" :
#line 19 "tokens.l"
return OP_AND;
            break;
          case 13: // rule tokens.l:20: "||" :
#line 20 "tokens.l"
return OP_OR;
            break;
          case 14: // rule tokens.l:21: "!" :
#line 21 "tokens.l"
return OP_NOT;


            break;
          case 15: // rule tokens.l:24: "=" :
#line 24 "tokens.l"
return OP_ASSIGN;


            break;
          case 16: // rule tokens.l:27: ";" :
#line 27 "tokens.l"
return SEMICOLON;
            break;
          case 17: // rule tokens.l:28: "," :
#line 28 "tokens.l"
return COMMA;
            break;
          case 18: // rule tokens.l:29: "(" :
#line 29 "tokens.l"
return LPAREN;
            break;
          case 19: // rule tokens.l:30: ")" :
#line 30 "tokens.l"
return RPAREN;
            break;
          case 20: // rule tokens.l:31: "{" :
#line 31 "tokens.l"
return LBRACE;
            break;
          case 21: // rule tokens.l:32: "}" :
#line 32 "tokens.l"
return RBRACE;

            break;
          case 22: // rule tokens.l:35: -?[0-9]+ :
#line 35 "tokens.l"
return CONST_INTEGER;

            break;
          case 23: // rule tokens.l:38: [a-zA-Z_][a-zA-Z0-9_]* :
#line 38 "tokens.l"
return IDENTIFIER;

            break;
          case 24: // rule tokens.l:41: [ \t\r\n]+ :
#line 41 "tokens.l"
/* no action: ignore all white space */

            break;
          case 25: // rule tokens.l:44: "//".* :
#line 44 "tokens.l"
/* no action: ignore single-line comments */

            break;
          case 26: // rule tokens.l:47: . :
#line 47 "tokens.l"
return ERROR;

            break;
        }
  }
}
